### ISSUE TITLE
if * is used in the WATCHED_NAMESPACES operator fails in onAdd method

### ISSUE THREAD

**Issue by Jiri-Kremser** [radanalyticsio/spark-operator#162]
### Describe the problem:

  * With couple of sentences describe the problem and its context.

#### Steps to reproduce:

  1.  set the `*` for the `WATCHED_NAMESPACES` env property in the manifest
  2. create the cluster using CR - `oc apply -f examples/cluster-cr.yaml`
  
#### Observed Results:
```
2018-12-21 13:45:24 INFO  AbstractOperator:354 - Custom resource 
CustomResourceSupport{kind='sparkcluster', apiVersion='radanalytics.io/v1', metadata=ObjectMeta(annotations={kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"radanalytics.io/v1","kind":"sparkcluster","metadata":{"annotations":{},"name":"my-spark-cluster","namespace":"default"},"spec":{"master":{"instances":"1"},"worker":{"instances":"2"}}}
}, clusterName=null, creationTimestamp=2018-12-21T13:45:24Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=1, initializers=null, labels=null, name=my-spark-cluster, namespace=default, ownerReferences=[], resourceVersion=28445, selfLink=/apis/radanalytics.io/v1/namespaces/default/sparkclusters/my-spark-cluster, uid=ab12b881-0526-11e9-abd7-0800275185bd, additionalProperties={})}
 in namespace * was ADDED
2018-12-21 13:45:24 INFO  AbstractOperator:419 - creating sparkcluster:  
my-spark-cluster
2018-12-21 13:45:25 WARN  WatchConnectionManager:201 - Exec Failure
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/api/v1/namespaces/*/services. Message: namespaces "*" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=namespaces, name=*, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=namespaces "*" not found, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:472)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:411)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:227)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:780)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:353)
	at io.fabric8.kubernetes.client.handlers.ServiceHandler.create(ServiceHandler.java:41)
	at io.fabric8.kubernetes.client.handlers.ServiceHandler.create(ServiceHandler.java:31)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:206)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:62)
	at io.radanalytics.operator.cluster.SparkClusterOperator.onAdd(SparkClusterOperator.java:45)
	at io.radanalytics.operator.cluster.SparkClusterOperator.onAdd(SparkClusterOperator.java:31)
	at io.radanalytics.operator.common.AbstractOperator.handleAction(AbstractOperator.java:420)
	at io.radanalytics.operator.common.AbstractOperator.access$000(AbstractOperator.java:42)
	at io.radanalytics.operator.common.AbstractOperator$2.eventReceived(AbstractOperator.java:362)
	at io.radanalytics.operator.common.AbstractOperator$2.eventReceived(AbstractOperator.java:351)
	at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:236)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```  
#### Expected Results:

No exception, cluster created.

**Comment by Jiri-Kremser** [comment]
fixed in https://github.com/radanalyticsio/spark-operator/pull/166
